# Generated by Django 5.1.5 on 2025-08-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_contactmessage_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['faculty', 'level', 'name']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AddField(
            model_name='faculty',
            name='academic_structure',
            field=models.CharField(choices=[('semester', 'Semester System'), ('year', 'Year System')], default='semester', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly name (e.g., 'bsccsit', 'bba', 'bbs')", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='total_levels',
            field=models.PositiveIntegerField(default=8, help_text='Number of semesters (8) or years (4)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.PositiveIntegerField(blank=True, help_text='Semester number (1-8) or Year number (1-4)', null=True),
        ),
    ]
