# Generated by Django 5.1.5 on 2025-09-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_viewed',
            field=models.DateTimeField(blank=True, help_text='Last time this resource was viewed', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='last_viewed',
            field=models.DateTimeField(blank=True, help_text='Last time this resource was viewed', null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='last_viewed',
            field=models.DateTimeField(blank=True, help_text='Last time this resource was viewed', null=True),
        ),
    ]
