# Generated by Django 5.1.5 on 2025-09-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_note_last_viewed_questionbank_last_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='last_viewed',
            field=models.DateTimeField(blank=True, help_text='Last time this resource was viewed', null=True),
        ),
    ]
