# Generated by Django 5.1.5 on 2025-09-09 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0014_mcqquestion_mcqoption_mcqquizsession_mcquseranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquseranswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='student_app.mcqoption'),
        ),
    ]
