# Generated by Django 5.1.5 on 2025-09-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0014_questionbanksolution'),
        ('student_app', '0015_alter_mcquseranswer_selected_option'),
    ]

    operations = [
    ]
