# Generated by Django 5.1.5 on 2025-09-09 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0016_auto_20250910_0141'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='mcqquizsession',
            name='subject',
        ),
        migrations.CreateModel(
            name='MCQQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.PositiveIntegerField()),
                ('title', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mcq_quizzes', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_quizzes', to='student_app.faculty')),
            ],
            options={
                'verbose_name': 'MCQ Quiz',
                'verbose_name_plural': 'MCQ Quizzes',
                'ordering': ['faculty', 'quiz_number'],
                'unique_together': {('faculty', 'quiz_number')},
            },
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='student_app.mcqquiz'),
        ),
        migrations.AddField(
            model_name='mcqquizsession',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='student_app.mcqquiz'),
        ),
    ]
