# Generated by Django 5.1.5 on 2025-10-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0016_merge_20250910_0142'),
        ('student_app', '0017_remove_mcqquestion_subject_and_more'),
    ]

    operations = [
    ]
